from numpy import *
m1=matrix('1,2,3;6 7 8;3,3,3')
print(m1)
print("===================")
print("Diagonal:",diagonal(m1))
print("===================")
print("Max:",m1.max())
print("===================")
print("Min:",m1.min())
print("===================")

print("+++++++++++++++++++++++")
m2=matrix('11,22,33;66 77 8;33,33,33')
print(m2)
print("+++++++++++++++++++++++")
print("Addition:")
print(m1+m2)
print("------------------------")
print("Subtraction:")
print(m1-m2)
print("***********************")
print("Multiplication:")
print(m1*m2)