from tkinter import *
root = Tk()
root.geometry('467x345')
topFrame=Frame(root)
topFrame.pack()
bottomFrame=Frame=Frame(root)
bottomFrame.pack()
b1=Button(topFrame,text="Button1",fg="red")
b2=Button(topFrame,text="Button2",fg="green")
b3=Button(topFrame,text="Button3",fg="yellow")
b4=Button(bottomFrame,text="Button4",fg="blue")
b5=Button(bottomFrame,text="Button4",fg="blue")
b1.pack(side=LEFT)
b2.pack(side=RIGHT)
b3.pack(side=LEFT)
b4.pack(side=LEFT)
b5.pack(side=LEFT)

root.mainloop()